"""Multi-campus university families with inherited earnings data.

Generated by ``scripts/detect_branch_campuses.py`` on 2026-05-05 (output:
``logs/branch_campus_detection_20260506T011440Z.json``), reviewed and
approved by Jeff on 2026-05-05.

Spec: docs/specs/feature-branch-campus-suppression.md.

Re-run ``scripts/detect_branch_campuses.py`` after each Scorecard data
refresh to verify this list is still accurate; diff the output against the
families enumerated below and update.

Format
------
``INSTITUTION_FAMILIES``
    Maps flagship UNITID -> sorted list of branch UNITIDs (excluding the
    flagship itself).
``SUPPRESSED_BRANCH_UNITIDS``
    Flat ``frozenset`` of all branch UNITIDs (= union of every value in
    ``INSTITUTION_FAMILIES``). The leaderboard query filters with
    ``WHERE unitid NOT IN (...)`` against this set.
``FAMILY_SIZE_BY_FLAGSHIP_UNITID``
    Maps flagship UNITID -> total family size (flagship + branches). Used
    to populate the ``family_size`` column on flagship rows.

Approved-list policy
--------------------
The detection script flagged 39 candidate families with at least one
inherited-earnings branch. Embry-Riddle (flagship UNITID 133553) was
**excluded** because Prescott / Daytona Beach / Worldwide are independently
accredited campuses and the inheritance signal sits on a thin overlap of
13 CIPs. All other 38 families are included.
"""

from __future__ import annotations

INSTITUTION_FAMILIES: dict[int, list[int]] = {
    # Strayer University (flagship: District of Columbia)
    131803: [
        233684, 430184, 443766, 443784, 449038, 450298, 450377, 453163,
        453215, 456621, 458885, 458919, 458955, 458964, 458973, 459994,
    ],
    # DeVry University (flagship: Illinois)
    482477: [
        482422, 482431, 482440, 482459, 482468, 482486, 482538, 482547,
        482556, 482565, 482574, 482608, 482617, 482635, 482653,
    ],
    # Chamberlain University (flagship: Illinois)
    454227: [
        454236, 454245, 457129, 460871, 466921, 466930, 475732, 475741,
        486938, 486947, 486956, 489344, 489353, 492759,
    ],
    # University of Phoenix (flagship: Arizona)
    484613: [
        380465, 405997, 420042, 432223, 442161, 445300, 484631, 484668,
        484677, 484710, 484729, 484756, 484783,
    ],
    # Herzing University (flagship: Madison)
    240392: [101365, 140340, 174154, 200785, 386472, 433536, 459842, 459851, 496973],
    # South University (flagship: Montgomery)
    101116: [133465, 139579, 251312, 449898, 459259, 459268, 475121, 480073, 481720],
    # Arizona College of Nursing (flagship: Tempe)
    421708: [487375, 494162, 494171, 495420, 495439, 495448, 495457, 497268],
    # Bryant & Stratton College (flagship: Buffalo)
    189583: [188517, 189565, 189592, 201469, 231785, 451750, 480091],
    # Remington College (flagship: Dallas Campus)
    223463: [366535, 377111, 412599, 445203, 451866, 460783, 497000],
    # Ohio University (flagship: Main Campus / Athens)
    204857: [204802, 204820, 204839, 204848, 204866],
    # Ottawa University (flagship: Phoenix)
    105367: [155627, 155636, 428259, 454582, 464226],
    # Rasmussen University (flagship: Minnesota)
    175014: [138309, 200013, 448673, 450571, 480657],
    # Hussian College (flagship: Philadelphia)
    212993: [220002, 363439, 368443, 444255],
    # Johnson & Wales University (flagship: Providence)
    217235: [414823, 439288, 445708, 460349],
    # Ohio State University (flagship: Main Campus / Columbus)
    204796: [204671, 204680, 204699, 204705],
    # Stevens-Henager College (flagship: Ogden)
    230621: [230630, 438151, 446677, 460899],
    # University of Connecticut (flagship: Storrs)
    129020: [436818, 436827, 436836, 463056],
    # West Coast University (flagship: Los Angeles)
    443331: [458210, 458229, 477039, 485272],
    # Antioch University (flagship: Yellow Springs)
    245892: [245838, 245847, 245883],
    # Brookline College (flagship: Phoenix)
    104090: [404055, 438179, 444088],
    # CEM College (flagship: San Juan)
    241517: [376224, 451741, 484835],
    # Caribbean University (flagship: Bayamon)
    241377: [241386, 363907, 363916],
    # Galen College of Nursing (flagship: Louisville)
    156471: [406024, 406033, 452948],
    # National American University (flagship: Rapid City)
    219204: [440749, 482325, 494269],
    # Platt College (flagship: Los Angeles)
    260789: [432384, 480204, 490878],
    # University of Pittsburgh (flagship: Pittsburgh Campus)
    215293: [215266, 215275, 215284],
    # California College San Diego (flagship: San Diego)
    485263: [474890, 478634],
    # City College (flagship: Hollywood)
    244233: [406547, 434539],
    # Dewey University (flagship: Hato Rey)
    443562: [449135, 469416],
    # EDP University of Puerto Rico (flagship: Villalba)
    492476: [494278, 494287],
    # Eagle Gate College (flagship: Murray)
    230366: [447421, 496326],
    # Linfield University (flagship: McMinnville)
    209065: [437316, 437325],
    # Miami University (flagship: Oxford)
    204024: [204006, 204015],
    # Pontifical Catholic University of Puerto Rico (flagship: Ponce)
    241410: [241395, 243586],
    # Rutgers University (flagship: New Brunswick)
    186380: [186371, 186399],
    # University of Cincinnati (flagship: Main Campus)
    201885: [201946, 201955],
    # University of Washington (flagship: Seattle Campus)
    236948: [377555, 377564],
    # University of Minnesota (flagship: Twin Cities)
    174066: [456959],
}


SUPPRESSED_BRANCH_UNITIDS: frozenset[int] = frozenset(
    branch
    for branches in INSTITUTION_FAMILIES.values()
    for branch in branches
)


FAMILY_SIZE_BY_FLAGSHIP_UNITID: dict[int, int] = {
    flagship: len(branches) + 1
    for flagship, branches in INSTITUTION_FAMILIES.items()
}


# Fail loudly at import time if a future edit slips a non-int through.
# Trusted-int discipline matters because the leaderboard SQL interpolates
# these values directly into a ``WHERE unitid NOT IN (...)`` clause. Use
# ``raise`` (not ``assert``) so the gate survives ``python -O`` /
# ``PYTHONOPTIMIZE=1``. Reject ``bool`` explicitly — it subclasses ``int``
# and would otherwise silently slip through.
def _validate_int(value: object, label: str) -> None:
    if isinstance(value, bool) or not isinstance(value, int):
        raise TypeError(
            f"{label} must be int (got {type(value).__name__}: {value!r})"
        )


for _flagship, _branches in INSTITUTION_FAMILIES.items():
    _validate_int(_flagship, "INSTITUTION_FAMILIES key")
    if not isinstance(_branches, list):
        raise TypeError(
            "INSTITUTION_FAMILIES value must be list "
            f"(flagship {_flagship!r}: got {type(_branches).__name__})"
        )
    for _branch in _branches:
        _validate_int(_branch, f"INSTITUTION_FAMILIES[{_flagship}] branch")
del _flagship, _branches, _branch
