import { motion } from "framer-motion";
import { springs } from "@/styles/motion";
import { ReceiptPanel } from "@/components/ReceiptPanel";

interface GemmaTakeProps {
  narrative: string;
  delay?: number;
}

export function GemmaTake({ narrative, delay = 0 }: GemmaTakeProps) {
  return (
    <motion.article
      id="region-gemma-take"
      aria-label="Gemma's career analysis"
      className="relative bg-bp-mid border border-border-subtle border-l-[3px] border-l-accent-insight rounded-xl p-6"
      initial={{ opacity: 0, y: 24 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ ...springs.smooth, delay }}
    >
      <div className="flex items-center gap-2 mb-3">
        <span className="text-body">💡</span>
        <span className="font-data text-micro text-accent-insight tracking-[2px] uppercase">
          GEMMA'S TAKE
        </span>
      </div>
      <p className="font-body text-body-lg text-text-primary max-w-[640px] leading-relaxed">
        {narrative}
      </p>
      <div className="absolute top-4 right-4">
        <ReceiptPanel id="gemma-take" label="Gemma's Take">
          <p>Generated by Gemma 4 based on:</p>
          <ul className="list-disc list-inside mt-1 space-y-0.5">
            <li>Pentagon stat profile</li>
            <li>Boss fight outcomes</li>
            <li>Career branch data</li>
            <li>Program-specific earnings</li>
          </ul>
        </ReceiptPanel>
      </div>
    </motion.article>
  );
}
