import type { TreeResponse } from "@/types/tree";

function delay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

const MOCK_TREE: TreeResponse = {
  tree: {
    soc_code: "13-2051",
    title: "Financial Analyst",
    level: 0,
    ern: 72,
    roi: 68,
    res: 45,
    grw: 61,
    aura: 38,
    median_wage: 95570,
    education: "Bachelor's degree",
    experience_years: null,
    experience_tier: "early",
    relatedness: null,
    boss_ai: "draw",
    boss_loans: "win",
    boss_market: "win",
    boss_burnout: "lose",
    boss_ceiling: "draw",
    children: [
      {
        soc_code: "11-3031",
        title: "Financial Manager",
        level: 1,
        ern: 85,
        roi: 74,
        res: 42,
        grw: 55,
        aura: 52,
        median_wage: 139790,
        education: "Bachelor's degree",
        experience_years: 5,
        experience_tier: "mid",
        relatedness: 2,
        boss_ai: "win",
        boss_loans: "unknown",
        boss_market: "win",
        boss_burnout: "draw",
        boss_ceiling: "unknown",
        children: [
          {
            soc_code: "11-1011",
            title: "Chief Executive",
            level: 2,
            ern: 95,
            roi: 82,
            res: 38,
            grw: 48,
            aura: 65,
            median_wage: 189520,
            education: "Master's degree",
            experience_years: 10,
            experience_tier: "senior",
            relatedness: 6,
            boss_ai: "win",
            boss_loans: "unknown",
            boss_market: "draw",
            boss_burnout: "lose",
            boss_ceiling: "unknown",
            children: [],
          },
          {
            soc_code: "11-3071",
            title: "Transportation & Storage Manager",
            level: 2,
            ern: 78,
            roi: 70,
            res: 55,
            grw: 58,
            aura: 48,
            median_wage: 105580,
            education: "Bachelor's degree",
            experience_years: 5,
            experience_tier: "mid",
            relatedness: 13,
            boss_ai: "draw",
            boss_loans: "unknown",
            boss_market: "win",
            boss_burnout: "draw",
            boss_ceiling: "unknown",
            children: [],
          },
        ],
      },
      {
        soc_code: "13-2061",
        title: "Financial Examiner",
        level: 1,
        ern: 70,
        roi: 72,
        res: 58,
        grw: 65,
        aura: 42,
        median_wage: 82210,
        education: "Bachelor's degree",
        experience_years: 1,
        experience_tier: "early",
        relatedness: 4,
        boss_ai: "draw",
        boss_loans: "unknown",
        boss_market: "win",
        boss_burnout: "win",
        boss_ceiling: "unknown",
        children: [
          {
            soc_code: "13-2052",
            title: "Personal Financial Advisor",
            level: 2,
            ern: 75,
            roi: 70,
            res: 62,
            grw: 58,
            aura: 70,
            median_wage: 94170,
            education: "Bachelor's degree",
            experience_years: 1,
            experience_tier: "early",
            relatedness: 8,
            boss_ai: "win",
            boss_loans: "unknown",
            boss_market: "draw",
            boss_burnout: "draw",
            boss_ceiling: "unknown",
            children: [],
          },
        ],
      },
      {
        soc_code: "15-2051",
        title: "Data Scientist",
        level: 1,
        ern: 80,
        roi: 75,
        res: 35,
        grw: 78,
        aura: 30,
        median_wage: 108020,
        education: "Master's degree",
        experience_years: null,
        experience_tier: "early",
        relatedness: 9,
        boss_ai: "lose",
        boss_loans: "unknown",
        boss_market: "win",
        boss_burnout: "draw",
        boss_ceiling: "unknown",
        children: [
          {
            soc_code: "15-2031",
            title: "Operations Research Analyst",
            level: 2,
            ern: 74,
            roi: 71,
            res: 40,
            grw: 72,
            aura: 35,
            median_wage: 82360,
            education: "Master's degree",
            experience_years: null,
            experience_tier: "mid",
            relatedness: 12,
            boss_ai: "lose",
            boss_loans: "unknown",
            boss_market: "win",
            boss_burnout: "win",
            boss_ceiling: "unknown",
            children: [],
          },
        ],
      },
      {
        soc_code: "13-1161",
        title: "Market Research Analyst",
        level: 1,
        ern: 62,
        roi: 65,
        res: 48,
        grw: 70,
        aura: 55,
        median_wage: 68230,
        education: "Bachelor's degree",
        experience_years: null,
        experience_tier: "entry",
        relatedness: 5,
        boss_ai: "draw",
        boss_loans: "unknown",
        boss_market: "win",
        boss_burnout: "win",
        boss_ceiling: "unknown",
        children: [],
      },
    ],
  },
  stats: {
    total_nodes: 9,
    max_depth_reached: 2,
    mcp_calls: 4,
    dead_ends: 2,
    wall_clock_ms: 3200,
  },
};

export async function mockGetTree(): Promise<TreeResponse> {
  await delay(1800);
  return MOCK_TREE;
}
