"""Pure-Python copy generation for PDF Report Exports.

See docs/specs/feature-pdf-report-exports.md §3.11 + §4 pdf_copy.py.

This module owns every PDF string that is NOT generated by Gemma. Verdict
lines, risk-level chip text, the per-row risk one-liners, the "where each
school pulls ahead" sentences, the data-coverage caveat, and the per-boss
advisory labels all live here. Forbidden vocabulary is enforced by two
frozensets — see RPG_TERMS_FORBIDDEN_IN_PDF (full PDF text) and
FORBIDDEN_IN_GEMMA_OUTPUT (Gemma question strings).
"""

from __future__ import annotations

import re
from collections.abc import Sequence
from functools import lru_cache
from math import floor
from typing import TYPE_CHECKING

from app.models.api import RiskLevel
from app.models.career import BossId, BossOutcome, Build
from app.services.boss_fights import BOSS_SPECS

if TYPE_CHECKING:
    from app.models.career import CareerOutcome


# ---------------------------------------------------------------------------
# Forbidden vocabulary (Decision #4 + genai-architect §10 C2/C3).
# ---------------------------------------------------------------------------

RPG_TERMS_FORBIDDEN_IN_PDF: frozenset[str] = frozenset({
    "boss", "bosses", "boss fight", "boss fights", "gauntlet",
    "fight ai", "fight student loans", "fight the market",
    "fight burnout", "fight the ceiling", "fight the future",
    "won", "lose", "lost", "draw",
    "win", "wins", "losses", "draws",
    "reroll", "rerolled", "build", "builds",
    "level up", "leveled up", "level-up",
})
# Asserted (case-insensitive, word-boundary regex) against the FULL rendered
# PDF text in test_pdf_copy.py. Stat abbreviations are deliberately omitted
# because the PDF chrome (pentagon, micro-table, glossary) renders them.

FORBIDDEN_IN_GEMMA_OUTPUT: frozenset[str] = (
    RPG_TERMS_FORBIDDEN_IN_PDF
    | frozenset({"ern", "roi", "res", "grw", "aura", "hmn"})
)
# Applied by pdf_questions.py to each Gemma-generated question string AFTER
# Pydantic validation. A match triggers gemma_path="fallback_malformed".


# ---------------------------------------------------------------------------
# Public voice validator — promoted from pdf_questions._has_forbidden_term so
# career_description.py and pdf_questions.py share one source of truth.
# Per @fp-architect §5 condition 6 / §2 Decision 16.
# ---------------------------------------------------------------------------


@lru_cache(maxsize=4)
def _forbidden_re(terms: frozenset[str]) -> re.Pattern[str]:
    """Compile a word-boundary, case-insensitive regex for ``terms``.

    Cached so callers paying per-text cost don't re-compile per call.
    The four expected entries are RPG_TERMS_FORBIDDEN_IN_PDF and
    FORBIDDEN_IN_GEMMA_OUTPUT (each used twice: career_description and
    pdf_questions); a tiny LRU is plenty.
    """
    return re.compile(
        r"\b(" + "|".join(re.escape(t) for t in terms) + r")\b",
        re.I,
    )


def contains_forbidden_term(text: str, terms: frozenset[str]) -> bool:
    """True iff ``text`` contains any term from ``terms`` (word-bounded, case-insensitive).

    Used by:
      - pdf_questions.py with FORBIDDEN_IN_GEMMA_OUTPUT (stricter — also
        rejects bare stat abbreviations because audience questions render
        them as glossary terms elsewhere on the same page).
      - career_description.py with RPG_TERMS_FORBIDDEN_IN_PDF (career
        descriptions can validly mention "earnings" but never "boss
        fight" — same ruleset as the rendered PDF text).
    """
    return bool(_forbidden_re(terms).search(text))


# ---------------------------------------------------------------------------
# Boss → advisory label (Decision #4 translation table; genai-architect §10 C5).
# Centralized here so pdf_export.py and pdf_questions.py cannot drift.
# ---------------------------------------------------------------------------

_BOSS_ADVISORY_LABEL: dict[BossId, str] = {
    "ai": "AI displacement risk",
    "loans": "Debt burden",
    "market": "Job market outlook",
    "burnout": "Burnout risk",
    "ceiling": "Earnings ceiling",
}

BOSS_ORDER: tuple[BossId, ...] = ("ai", "loans", "market", "burnout", "ceiling")


def boss_advisory_label(boss_id: BossId) -> str:
    """Decision #4 advisory label for a boss. Stable + import-safe."""
    return _BOSS_ADVISORY_LABEL[boss_id]


# ---------------------------------------------------------------------------
# Risk-level mapping. Deterministic per-boss thresholds (no dataset cuts).
# ---------------------------------------------------------------------------


def risk_level_for_boss(boss_id: BossId, raw_score: int | None) -> RiskLevel:
    """Map raw_score to advisory bucket per the §5 deterministic table.

    raw_score is None → "Insufficient" (NEVER "High"; the missing-data-
    is-not-zero rule per @fp-data-reviewer round-1 ruling).

    Otherwise:
        raw_score >= win_at_or_above   → "Low"
        raw_score >= draw_at_or_above  → "Moderate"
        raw_score >= floor(draw / 2)   → "Elevated"
        raw_score <  floor(draw / 2)   → "High"
    """
    if raw_score is None:
        return "Insufficient"
    spec = BOSS_SPECS[boss_id]
    if raw_score >= spec.win_at_or_above:
        return "Low"
    if raw_score >= spec.draw_at_or_above:
        return "Moderate"
    if raw_score >= floor(spec.draw_at_or_above / 2):
        return "Elevated"
    return "High"


def risk_level_from_outcome(boss_id: BossId, outcome: BossOutcome, raw_score: int | None) -> RiskLevel:
    """Convenience: map a BossFightResult shape to RiskLevel.

    Prefers the deterministic raw_score path; only falls back to outcome
    when raw_score is unavailable. "unknown" → Insufficient.
    """
    if outcome == "unknown":
        return "Insufficient"
    return risk_level_for_boss(boss_id, raw_score)


# ---------------------------------------------------------------------------
# Verdict line (parameterized; not Gemma-generated).
# ---------------------------------------------------------------------------


def _risk_level_counts(build: Build) -> dict[RiskLevel, int]:
    """Tally RiskLevel across the 5 boss fights."""
    counts: dict[RiskLevel, int] = {
        "Low": 0, "Moderate": 0, "Elevated": 0, "High": 0, "Insufficient": 0,
    }
    for fight in build.gauntlet.fights:
        level = risk_level_from_outcome(fight.boss, fight.result, fight.raw_score)
        counts[level] += 1
    return counts


def _risk_summary(counts: dict[RiskLevel, int]) -> str:
    """First-match-wins risk-summary bucket selection (§3.11.1)."""
    # "insufficient" wins over any other bucket when 3+ rows are unknown —
    # the PDF refuses to summarize what it cannot honestly observe.
    if counts["Insufficient"] >= 3:
        return "the data is partial — read the risk profile below before drawing conclusions"
    if counts["Low"] >= 4 and counts["High"] == 0:
        return "the data shows steady fundamentals"
    if counts["High"] == 0 and counts["Elevated"] <= 1 and counts["Low"] >= 2:
        return "the data shows steady fundamentals with one or two factors to watch"
    if counts["High"] >= 2:
        return "the data flags multiple risk factors worth a closer look"
    return "the data shows two or more risk factors worth weighing"


def _roi_summary(dte: float | None) -> str:
    """ROI-summary bucket on debt_to_earnings_annual (§3.11.1).

    Thresholds mirror roiLabelKey() bins in FinancesCard.tsx (8/18/30%) so
    the PDF and on-screen ROI label cannot disagree.
    """
    if dte is None:
        return "Cost-to-earnings is unavailable for this program"
    if dte < 0.08:
        return "Cost recovery looks strong against year-1 earnings"
    if dte < 0.18:
        return "Cost is in line with year-1 earnings"
    if dte < 0.30:
        return "Cost is sizable against year-1 earnings"
    return "Cost is high relative to year-1 earnings"


def verdict_line(build: Build) -> str:
    """One-line display verdict for the My Build PDF page-1 hero.

    Format: "{Major} at {School}: {risk_summary}. {roi_summary}."
    Capitalization: lowercase after the colon, sentence-case after the
    period. Max 200 chars (P2 budget test).
    """
    major = build.career.program_name or build.major_text or "Program"
    school = build.school_name
    counts = _risk_level_counts(build)
    risk = _risk_summary(counts)
    roi = _roi_summary(build.career.debt_to_earnings_annual)
    return f"{major} at {school}: {risk}. {roi}."


# ---------------------------------------------------------------------------
# Risk one-liner — 5 bosses × 5 levels = 25 strings (with anchor fall-back).
# ---------------------------------------------------------------------------


_RISK_ANCHOR_TEMPLATES: dict[BossId, dict[RiskLevel, str]] = {
    "ai": {
        "Low": "AI exposure for this occupation sits at the {p:.0f}th percentile — most core tasks remain human-led.",
        "Moderate": "AI exposure for this occupation sits at the {p:.0f}th percentile — some routine tasks are increasingly automatable.",
        "Elevated": "AI exposure sits at the {p:.0f}th percentile — a meaningful share of tasks could shift to AI within a decade.",
        "High": "AI exposure sits at the {p:.0f}th percentile — most routine tasks could be performed by AI within a decade.",
        "Insufficient": "Data unavailable for this program.",
    },
    "loans": {
        "Low": "Modeled year-1 debt service is {v:.0f}% of starting earnings — comfortably below the 10% guideline.",
        "Moderate": "Modeled year-1 debt service is {v:.0f}% of starting earnings — within the standard manageable range.",
        "Elevated": "Modeled year-1 debt service is {v:.0f}% of starting earnings — above the recommended ceiling for new graduates.",
        "High": "Modeled year-1 debt service is {v:.0f}% of starting earnings — well above what early-career income typically supports.",
        "Insufficient": "Data unavailable for this program.",
    },
    "market": {
        # numeric anchor often unavailable on CareerOutcome — see
        # _market_anchor() below; we substitute growth_category when a
        # numeric pct is missing and otherwise fall back to level-only.
        "Low": "BLS classifies this as a growing field ({label}).",
        "Moderate": "BLS classifies this as roughly steady demand ({label}).",
        "Elevated": "BLS projects slower-than-average growth ({label}).",
        "High": "BLS classifies this as a contracting field ({label}).",
        "Insufficient": "Data unavailable for this program.",
    },
    "burnout": {
        "Low": "O*NET task profile shows {driver} — within typical workload patterns.",
        "Moderate": "O*NET task profile shows {driver} — a real demand worth understanding before committing.",
        "Elevated": "O*NET task profile shows {driver} — a known burnout driver in this occupation.",
        "High": "O*NET task profile shows {driver} — a leading burnout factor in this occupation.",
        "Insufficient": "Data unavailable for this program.",
    },
    "ceiling": {
        "Low": "Year-1 75th-percentile wage is ${v:,.0f} — meaningful upside above the median.",
        "Moderate": "Year-1 75th-percentile wage is ${v:,.0f} — modest upside above the median.",
        "Elevated": "Year-1 75th-percentile wage is ${v:,.0f} — limited room to grow above the median.",
        "High": "Year-1 75th-percentile wage is ${v:,.0f} — earnings plateau early in this occupation.",
        "Insufficient": "Data unavailable for this program.",
    },
}

# Level-only fallback when anchor data is missing but level is known.
# Drops the data clause cleanly so no "None%" strings ever leak.
_RISK_LEVEL_ONLY: dict[BossId, dict[RiskLevel, str]] = {
    "ai": {
        "Low": "AI displacement risk is low for this occupation.",
        "Moderate": "AI displacement risk is moderate for this occupation.",
        "Elevated": "AI displacement risk is elevated for this occupation.",
        "High": "AI displacement risk is high for this occupation.",
        "Insufficient": "Data unavailable for this program.",
    },
    "loans": {
        "Low": "Modeled debt is comfortable against starting earnings.",
        "Moderate": "Modeled debt is within the standard manageable range.",
        "Elevated": "Modeled debt is above the recommended ceiling for new graduates.",
        "High": "Modeled debt is well above what early-career income typically supports.",
        "Insufficient": "Data unavailable for this program.",
    },
    "market": {
        "Low": "BLS outlook for this occupation is favorable.",
        "Moderate": "BLS outlook for this occupation is roughly steady.",
        "Elevated": "BLS outlook is slower than the all-occupations average.",
        "High": "BLS outlook is contracting for this occupation.",
        "Insufficient": "Data unavailable for this program.",
    },
    "burnout": {
        "Low": "Workload patterns for this occupation fall within typical ranges.",
        "Moderate": "This occupation has at least one demand worth understanding.",
        "Elevated": "This occupation has known burnout drivers.",
        "High": "This occupation is a leading source of burnout.",
        "Insufficient": "Data unavailable for this program.",
    },
    "ceiling": {
        "Low": "Earnings ceiling sits well above the median for this occupation.",
        "Moderate": "Earnings ceiling shows modest upside above the median.",
        "Elevated": "Earnings ceiling shows limited room to grow above the median.",
        "High": "Earnings plateau early in this occupation.",
        "Insufficient": "Data unavailable for this program.",
    },
}


def _ai_anchor(career: CareerOutcome) -> float | None:
    """AI exposure percentile (0..100). None when missing."""
    p = career.adoption_percentile
    if p is None:
        return None
    # Composite percentile is stored 0..1 (per ai_exposure_composite spec)
    # OR 0..100 depending on pipeline version. Normalize to 0..100.
    return p * 100 if p <= 1.0 else p


def _market_anchor(career: CareerOutcome) -> str | None:
    """Growth_category or None. We don't have a numeric pct on CareerOutcome."""
    label = career.growth_category
    return label if label else None


def _burnout_anchor(career: CareerOutcome) -> str | None:
    """First burnout driver from the O*NET list, or None."""
    drivers = career.burnout_drivers
    if not drivers:
        return None
    first = drivers[0]
    if isinstance(first, dict):
        # Common keys observed: "label", "driver", "name". Try in order.
        for key in ("label", "driver", "name", "title"):
            v = first.get(key)
            if isinstance(v, str) and v:
                return v
    elif isinstance(first, str) and first:
        return first
    return None


def risk_one_liner(boss_id: BossId, level: RiskLevel, build: Build) -> str:
    """One-sentence advisory copy for a (boss_id, level) pair.

    Anchors are read from build.career, never recomputed. When the named
    anchor is None, falls back to the level-only template so no "None%"
    or "${None}" strings can ever leak.
    """
    career = build.career
    if level == "Insufficient":
        # Same string for all 5 bosses — counselor-scanning aid (§3.11.2).
        return "Data unavailable for this program."

    template = _RISK_ANCHOR_TEMPLATES[boss_id][level]
    fallback = _RISK_LEVEL_ONLY[boss_id][level]

    if boss_id == "ai":
        p = _ai_anchor(career)
        return template.format(p=p) if p is not None else fallback
    if boss_id == "loans":
        dte = career.debt_to_earnings_annual
        if dte is None:
            return fallback
        return template.format(v=dte * 100)
    if boss_id == "market":
        label = _market_anchor(career)
        return template.format(label=label) if label else fallback
    if boss_id == "burnout":
        driver = _burnout_anchor(career)
        return template.format(driver=driver) if driver else fallback
    if boss_id == "ceiling":
        v = career.earnings_1yr_p75
        return template.format(v=v) if v is not None else fallback
    return fallback


# ---------------------------------------------------------------------------
# "Where each school pulls ahead" template (Comparison PDF, §3.11.6).
# ---------------------------------------------------------------------------

# Stat-priority order for picking the top-2 leading factors.
_LEADING_PRIORITY: tuple[str, ...] = (
    "Earnings", "ROI", "AI Resilience", "Growth", "Brand Gravity",
    "4-year cost", "Modeled debt", "Year-1 earnings", "Debt-to-earnings ratio",
    "AI displacement risk", "Debt burden", "Job market outlook",
    "Burnout risk", "Earnings ceiling",
)


def _stat_value(build: Build, key: str) -> int | None:
    return getattr(build.career.stats, key, None)


def _leading_factors_for(build: Build, others: Sequence[Build]) -> list[str]:
    """Return the human-labeled factors this build leads on vs the others.

    "Lead" semantics per @fp-data-reviewer §5 leading-direction table:
    - higher wins for ERN/ROI/RES/GRW/AURA + year-1 earnings
    - lower wins for 4-year cost / modeled debt / debt-to-earnings
    - ties → no one leads on that row (the build doesn't get credit).
    - all peers None → no one leads (the build doesn't get a free win
      against missing data; staff-engineer A4 fix).
    """
    leaders: list[str] = []
    stat_dirs = (
        ("Earnings", "ern", "high"),
        ("ROI", "roi", "high"),
        ("AI Resilience", "res", "high"),
        ("Growth", "grw", "high"),
        ("Brand Gravity", "aura", "high"),
    )
    for label, key, _direction in stat_dirs:
        my = _stat_value(build, key)
        if my is None:
            continue
        peer_values = [_stat_value(o, key) for o in others]
        peer_real = [v for v in peer_values if v is not None]
        if not peer_real:
            continue  # No comparison possible — don't claim leadership.
        if all(my > v for v in peer_real):
            leaders.append(label)

    cost_dirs = (
        ("4-year cost", "published_cost_4yr", "low"),
        ("Modeled debt", "modeled_total_debt", "low"),
        ("Year-1 earnings", "earnings_1yr_median", "high"),
        ("Debt-to-earnings ratio", "debt_to_earnings_annual", "low"),
    )
    for label, attr, direction in cost_dirs:
        my = getattr(build.career, attr, None)
        if my is None:
            continue
        peer_values = [getattr(o.career, attr, None) for o in others]
        peer_real = [v for v in peer_values if v is not None]
        if not peer_real:
            continue
        cmp = (
            (lambda a, b: a < b)
            if direction == "low"
            else (lambda a, b: a > b)
        )
        if all(cmp(my, v) for v in peer_real):  # type: ignore[no-untyped-call]
            leaders.append(label)

    return leaders


def where_each_pulls_ahead(builds: list[Build]) -> list[str]:
    """One sentence per build identifying its top-2 leading factors.

    Output length == len(builds). Order matches input order.
    """
    output: list[str] = []
    for i, build in enumerate(builds):
        others = [b for j, b in enumerate(builds) if j != i]
        leaders = _leading_factors_for(build, others)
        # Apply priority ordering: the two leading factors a counselor
        # cares about most, named first.
        leaders.sort(key=lambda f: _LEADING_PRIORITY.index(f) if f in _LEADING_PRIORITY else 99)
        school = build.school_name
        if len(leaders) >= 2:
            output.append(f"{school} — leads on {leaders[0]} and {leaders[1]}.")
        elif len(leaders) == 1:
            output.append(f"{school} — leads on {leaders[0]}.")
        else:
            output.append(f"{school} — no clear leader on these factors; trade-offs are even.")
    return output


# ---------------------------------------------------------------------------
# Data-coverage caveat (§3.11.5).
# ---------------------------------------------------------------------------


_COVERAGE_CAVEATS: dict[str, str] = {
    "scorecard_only": (
        "Note: occupational task data is partial for this program. "
        "Earnings, cost, and debt figures are full coverage."
    ),
    "partial_no_onet": (
        "Note: O*NET task detail is unavailable for this occupation. "
        "Earnings, cost, and debt figures are full coverage."
    ),
}


def data_coverage_caveat(build: Build) -> str | None:
    """Conditional one-line caveat for the page-1 header strip.

    Returns None when match_quality is "full" (no caveat rendered) or
    when the field is None/unknown. Distinct from the suppressed
    CIP-substitution caveat per feedback_no_substitution_caveat.md.
    """
    mq = build.career.match_quality
    if mq is None or mq == "full":
        return None
    return _COVERAGE_CAVEATS.get(mq)
